### ISSUE TITLE
Server Installer fails to download minecraft files

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/modpacksch-serverdownloader#18]
Log File:
https://pste.me/@/mz21CAv9VT8/

Using FTB Skies 1.0.7
Windows 10

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256

**Comment by Gaz492** [comment]
fixed f1195888edc5ca1b46219044bf83248ff05fc3ec

**Comment by Wtfigohere** [comment]
I am still getting the same thing.
Linux.
downloaded the a new copy of the server install.

"2023/04/28 17:05:53 Downloaded 1130 successful, 4 failed, 0 incomplete.
Some downloads failed. Would you like to continue anyway? (y/n) [y]"

**Comment by Wtfigohere** [comment]
copy/paste problem?
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar: server returned 404 Not Found


if i remove https://libraries.minecraft.net/ and go to the link after i can download.

**Comment by manmaed** [comment]
this might fix #17 as well

**Comment by Wtfigohere** [comment]
nope... this is a problem in the script or something injecting the start of the URL multiple times and incorrect.
Error downloading ------https://libraries.minecraft.net/------https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found

**Comment by manmaed** [comment]
This has now been fixed
